swagger: '2.0'
info:
  version: 1.0.0
  title: HabitApp API
  description: API documentation for HabitApp.
host: api.habitapp.com
basePath: /
schemes:
  - https
paths:
  /auth/signup:
    post:
      summary: Sign up a new user
      description: Creates a new user account.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              full_name:
                type: string
              email:
                type: string
              phone:
                type: string
              profile_photo:
                type: string
                format: binary
              username:
                type: string
              password:
                type: string
            required:
              - full_name
              - email
              - password
      responses:
        '200':
          description: User created successfully
        '400':
          description: Bad request
  /auth/login:
    post:
      summary: User login
      description: Logs in an existing user.
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
            required:
              - email
              - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials
  /user/{username}:
    get:
      summary: Get user profile
      description: Retrieves profile details for a specific user.
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        '200':
          description: User profile retrieved successfully
        '404':
          description: User not found
    patch:
      summary: Update user profile
      description: Updates profile details for a specific user.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone:
                type: string
              profile_photo:
                type: string
                format: binary
      responses:
        '200':
          description: Profile updated successfully
    delete:
      summary: Delete user account
      description: Deletes a user's account.
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        '204':
          description: User account deleted successfully
        '404':
          description: User not found
  /habits/{username}:
    post:
      summary: Create a new habit
      description: Creates a new habit for the specified user.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              habit:
                type: string
            required:
              - habit
      responses:
        '201':
          description: Habit created successfully
        '400':
          description: Bad request
  /habits/{username}/{habit_id}/detailed-habit:
    patch:
      summary: Update detailed habit
      description: Adds or updates the detailed habit description.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: path
          name: habit_id
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              detailed_habit:
                type: string
      responses:
        '200':
          description: Detailed habit updated successfully
        '400':
          description: Bad request
        '404':
          description: Habit not found
  /habits/{username}/{habit_id}/complete:
    patch:
      summary: Mark habit as complete
      description: Marks a user's habit as complete and triggers a follow-up in 3 months.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: path
          name: habit_id
          required: true
          type: string
      responses:
        '200':
          description: Habit marked as complete successfully
        '404':
          description: User or habit not found
  /team-members/{username}:
    get:
      summary: Get all team members
      description: Retrieves all team members for a user.
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        '200':
          description: Team members retrieved successfully
    post:
      summary: Add a new team member
      description: Adds a new team member to a specific habit.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              habit:
                type: string
              role:
                type: string
                enum:
                  - cohort
                  - leader
            required:
              - firstName
              - habit
              - role
      responses:
        '201':
          description: Team member added successfully
        '400':
          description: Bad request
    put:
      summary: Update a team member
      description: Updates a team member's details.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              role:
                type: string
                enum:
                  - cohort
                  - leader
      responses:
        '200':
          description: Team member updated successfully
    delete:
      summary: Delete a team member
      description: Deletes a team member.
      parameters:
        - in: path
          name: username
          required: true
          type: string
      responses:
        '204':
          description: Team member deleted successfully
  /feedback/{username}:
    post:
      summary: Submit feedback
      description: Allows a team member to submit feedback for a habit.
      parameters:
        - in: path
          name: username
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              habit:
                type: string
              teamMember:
                type: string
              feedbackText:
                type: string
      responses:
        '201':
          description: Feedback submitted successfully
        '400':
          description: Bad request

